version: '3'
services:
  node:
    user: node
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/app:delegated
      - node_modules:/app/node_modules
    tty: true

  mongo:
    image: mongo:5.0.6
    restart: always
    ports:
      - 27017:27017
    volumes:
      - /data/db

volumes:
  node_modules:
